### PR TITLE
Fix attribute class on initial render (and improve size/performance)

### LINKED ISSUE #9: attribute: 'class' does not work on first render
Using `attribute: 'class'`, the first SSR from next does not appear add the class to the html document.

### PR DESCRIPTION
**Pull request by pacocoursey**
Builds on #10 and fixes #9

### CODE REVIEW

File: index.tsx [hunk 1]
```diff
@@ -115,7 +113,7 @@ export const ThemeProvider: React.FC<ThemeProviderProps> = ({
 
   useEffect(() => {
     const handleStorage = (e: StorageEvent) => {
-      if (e.key !== 'theme') {
+      if (e.key !== storageKey) {
```
Comment (pacocoursey) [inline index.tsx:116]: Fixes another bug in which localStorage syncing wouldn't work if specifying a custom `storageKey`
